apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-routes
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: apisix
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/strikehand/kubernetes/tree/8ab93fbdfb33d5a049c914e3d41e7f5838221c39/ApisixRoutes'
    targetRevision: 'master'
    helm:
      valueFiles:
      - ApisixRoutes/TestUpstreams.yaml
  project: apisix-routes 
