apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apisix-routes
  namespace: argocd
spec:
  description: Project for Apisix Routes deploy
  sourceRepos:
  - 'https://gitlab.bankspb.ru/integration-platform/apisix-routes.git'
  destinations:
  - namespace: apisix
    server: "*"
    name: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
