apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap/
    targetRevision: 4.3.3
    chart: openldap-stack-ha
    helm:
      values: |
        global:
          ldapDomain: "openldap.openldap.org"
          adminUser: "admin"
          adminPassword: admin12345678
          configUser: "admin"
          configPassword: admin12345678
          ldapPort: 389
          sslLdapPort: 636

        replicaCount: 1
        readOnlyReplicaCount: 0

        image:
          repository: jpgouin/openldap
          tag: 2.6.9-fix
          pullPolicy: Always
          pullSecrets: []

        logLevel: info

        initSchema:
          image:
            repository: debian
            tag: latest
            pullPolicy: Always

        env:
          BITNAMI_DEBUG: "false"
          LDAP_LOGLEVEL: "256"
          LDAP_REQUIRE_TLS: "false"
          LDAPTLS_REQCERT: "never"
          LDAP_ENABLE_TLS: "yes"
          LDAP_SKIP_DEFAULT_TREE: "no"
          LDAP_ALLOW_ANON_BINDING: 'no'

        replication:
          enabled: false

        persistence:
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 8Gi

        podSecurityContext:
          enabled: true
          fsGroup: 1001

        containerSecurityContext:
          enabled: false

        serviceAccount:
          create: true

        initTLSSecret:
          tls_enabled: false
          image:
            registry: docker.io
            repository: alpine/openssl
            tag: latest
            pullPolicy: IfNotPresent

        volumePermissions:
          enabled: false

        livenessProbe:
          enabled: true
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          enabled: true
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        startupProbe:
          enabled: true
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 30

        test:
          enabled: false

        ltb-passwd:
          enabled : false

        phpldapadmin:
          enabled: true
          image:
            tag: 0.9.0
          env:
            PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
          ingress:
            enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: openldap
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
