{{- range .Values.apisixRoutes }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  http:
    - name: {{ .routeName }}
      match:
        hosts:
          - {{ .host }}
        paths:
          - {{ .path }}
        methods:
        {{- range .methods }}
          - {{ . }}
        {{- end }}
      {{- if .plugins }}
      plugins:
        {{- range .plugins }}
        - name: {{ .name }}
          enable: {{ .enable | default true }}
          {{- if .config }}
          config:
{{ toYaml .config | indent 12 }}
          {{- end }}
          {{- if .secretRef }}
          secretRef:
{{ toYaml .secretRef | indent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .upstreamRef }}
      upstream:
        name: {{ .upstreamRef }}
        namespace: {{ .namespace }}
      {{- end }}
{{- end }}

{{- range .Values.apisixUpstreams }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  type: {{ .type | default "roundrobin" }}
  scheme: {{ .scheme | default "https" }}
  pass_host: {{ .pass_host | default "pass" }}
  timeout:
{{ toYaml .timeout | indent 4 }}
  keepalive_pool:
{{ toYaml .keepalive_pool | indent 4 }}
  nodes:
{{ toYaml .nodes | indent 4 }}
{{- end }}
