apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort  # Используйте NodePort для доступа к сервису извне кластера.
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000  # Вы можете выбрать любой доступный порт в диапазоне 30000-32767.
  selector:
    app: grafana
