apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Используйте NodePort для доступа к сервису извне кластера.
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Вы можете выбрать любой доступный порт в диапазоне 30000-32767.
  selector:
    app: nginx