apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix-auth-mapper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/strikehand/kubernetes.git
    targetRevision: master
    path: Helm/apisix-auth-mapper
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
